### ISSUE TITLE
Blender 3.3 issue

### ISSUE THREAD

**Issue by ForteDexe** [TehMerow/Blender_Nord_Dark_Theme#2]
I have this issue when install the theme on blender 3.3
![image](https://user-images.githubusercontent.com/57673412/195586511-30c1f5e1-a741-4c5a-82ac-1750cd162c30.png)

Pls help me fix or diagnose if you have time :).

**Comment by TehMerow** [comment]
That appears to me by bad, whoops! Some git shenanigans seemed to have broken the file and I didn't notice 😖
I'm pretty sure I've fixed it and updated the release
Happy Blendering!

**Comment by ForteDexe** [comment]
Awesome, it's worked, thank you ^^.
